name: practice_project_parallalJobs

on:
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:  
    runs-on: ubuntu-latest
    steps:
      - name: get code into the runner 
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: build the project
        run: npm run deploy
      - name: deploy
        run: echo "Deploying the project..."   
          

      
  
 
